### ISSUE TITLE
Help the file!

### ISSUE THREAD

**Issue by getengqing** [rinkako/DeepID#1]
I can't find your prototxt files(lfw_deepid.prototxt   sasia_deepid.prototxt   deepidSolver.prototxt), can you share ?

**Comment by rinkako** [comment]
this prototxt file will be generated by running myDeepid.py. But actually, i do not suggest you to use this code since its performance is inferior. I'm now working on improve it and many parameters are changed so this code may be no value for you.

**Comment by getengqing** [comment]
Thanks！Can your share the new working ?

**Comment by rinkako** [comment]
after I achieve the performance in the paper I'll push it to this repository :)

**Comment by zhanglaplace** [comment]
hi, when training the deepid Model, whether we should process one training image to 60 patchs,each path as a traing pic;
